nosana:
  description: Run Test 2


global:
  image: node:16
  environment:
    SECRET: 
      type: "nosana/secret"
      endpoint: "https://secrets.k8s.prd.nos.ci"
      value: SECRET
  trigger:
    branch:
      - all

jobs:
  - name: install-deps and run test
    commands: 
      - echo answer is $SECRET
      - npm ci
      - npm run test