nosana:
  description: Run Test 2


global:
  #image: registry.hub.docker.com/jeisses/rtb_monitor:v4
  image: ubuntu:latest
  image-pull-secret:
    username: jesse
    password:
      - type: "nosana/secret"
        endpoint: "https://secrets.k8s.dev.nos.ci"
        value: DOCKERHUBPASS
  environment:
    SECRET: 
      type: "nosana/secret"
      endpoint: "https://secrets.k8s.dev.nos.ci"
      value: SECRET

jobs:
  - name: install-deps and run test
    #artifacts:
     # - name: data
      #  paths:
       #   - "*.yml"
        #  - "**/*.js*"   
    commands: 
      - pwd
      - ls
      - echo answer is $SECRET
      #- npm install
      #- npm run test
      - sleep 10
    trigger:
      push:
        branches:
          - main
      
  - name: check artifact
    resources:
      - name: data
        path: data
    commands:
      - ls -lha data
      - ls -lha data/test
      - ls -lha data/node_modules

  - name: devnet
    commands:
      - echo "only trigger on dev branch"
    trigger:
      push:
        branches:
          - dev
