nosana:
  description: Run Test 2


global:
  image: registry.hub.docker.com/jeisses/rtb_monitor:v4
  environment:
    SECRET: 
      type: "nosana/secret"
      endpoint: "https://secrets.k8s.dev.nos.ci"
      value: SECRET
  trigger:
    branch:
      - all

jobs:
  - name: install-deps and run test
    artifacts:
      - name: data
        paths:
          - "*.yml"
          - "**/*.js*"   
    commands: 
      - echo answer is $SECRET
      - npm install
      - npm run test
      
  - name: check artifact
    resources:
      - name: data
        path: data
    commands:
      - ls -lha data
      - ls -lha data/test
      - ls -lha data/node_modules